[build]
  # Use legacy-peer-deps to avoid peer dependency issues
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "build"

  # Environment variables for the build environment
  [build.environment]
    NODE_ENV = "production"
    NODE_VERSION = "16"

# Optional: Set environment variables for production deploy context
[context.production.environment]
  NODE_ENV = "production"
